//Root file of the module system. This file can be used to import and export functions,
//  classes, or variables from other files in the module.
//For example, you can import the `sum` function from `sum.js` and use it in this file.
//  You can also export functions, classes, or variables from this file to be used in other files.

// module.exports  -> This is used to export functions, classes, or variables from a file.
//  You can assign a function, class, or variable to `module.exports` to make it available for
//  import in other files.
//require -> This is used to import functions, classes, or variables from other files.
//  You can use `require` to import a file and access its exported functions, classes, or variables.
//  For example, you can use `const sum = require('./sum');` to import the `sum` function from `sum.js`
//  and then use it in this file.

//importing the functions from first-module.js using require. We can assign the imported module to
//  a variable, and then we can use the functions from that module. 

const firstModule = require('./first-module');// A CommonJS module. It can be converted into an ES module
//  by changing the file extension to .mjs and using export
//  and import statements instead of module.exports and require.
//  We can use the functions from first-module.js by accessing them through the `firstModule` variable.
//  For example, we can use `firstModule.add(5, 10)` to call the `add` function from `first-module.js`
//  and get the result.

console.log(firstModule.add(10, 20)); // Output: 30
console.log(firstModule.subtract(20, 10)); // Output: 10
console.log(firstModule.divide(20, 10)); // Output: 2
console.log(firstModule.divide(20, 0)); // Output: Error: Divide by zero is not allowed

//try & catch block is used to handle errors that may occur during the execution of the code. In this case, we are trying to call the `divide` function with a divisor of 0, which will throw an error. We can catch that error and log it to the console instead of crashing the program.

try {
    console.log('Trying tot divide by zero');
    let result = firstModule.divide(0, 10);
} catch (error) {
  console.error('Caught an error:', error.message);
}
// module wrapper -> This is a function that wraps the code of each module. It provides
//  a local scope for the module's variables and functions, and it also provides
// the `exports`, `require`, `module`, `__filename`, and `__dirname` variables to the module.
// The module wrapper function is automatically generated by Node.js when a module is loaded,
//  and it allows modules to be self-contained and to avoid polluting the global scope.

//(function (exports, require, module, __filename, __dirname) {
  // The code of the module goes here. This is where you can define functions, classes, or variables
  //  that are specific to this module. You can also use the `exports` object to export functions,
  //  classes, or variables from this module to be used in other modules.
//});